# ?? ?? ??
server:
  port: 8080 # ?????? ??? ??? ?? ??. ???? 8080???.
  servlet:
    contextPath: /api/v1/user # ?? ?? URL ?? ?? ?? ??. ?? ??, `/api/v1/user/hello`? ?? ?????.

# Spring ??? ?? ? JPA ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC ???? ????.
    url: jdbc:mysql://localhost:3307/user_service?createDatabaseIfNotExist=true # ?????? URL. `createDatabaseIfNotExist=true` ??? ??????? ???? ?? ? ?? ?????.
    username: admin # ?????? ??? ?? ??? ??.
    password: 1234 # ?????? ??? ?? ????.
    hikari:
      auto-commit: false # HikariCP ??? ?? ?? ?? ??. false? ??, ??????? ????? ????? ????? ???? ???.
      connection-test-query: SELECT 1 # ??? ?? ??? ????? ???? ?? ???? ??.
      minimum-idle: 10 # ??? ?? ??? ?? ?? ??? ?.
      maximum-pool-size: 20 # ??? ??? ??? ?? ??? ?.

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL 8용 Hibernate 방언.
    hibernate:
      ddl-auto: update # Hibernate가 필요한 변경사항만 데이터베이스 스키마에 적용.
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 포맷.
        hbm2ddl.auto: update # 데이터베이스 스키마를 최신 상태로 유지.
    open-in-view: false # Open Session In View 패턴 비활성화.
    show-sql: true # 실행된 SQL 로깅.


jwt:
  secret: 6rCA64KY64uk652866eI67CU7IKs7JWE7J6Q7LCo7Lm07YOA7YyM7ZWY


# MongoDB ?? ??(?? ?? ???? ???? ??)
#  data:
#    mongodb:
#      uri: mongodb://admin:1234@localhost:27017/admin # MongoDB ?? URI. ??? ??, ????, ???, ??, ?????? ??? ?????.

# ?? ??
logging:
  level:
    org.hibernate.SQL: debug # Hibernate? ???? SQL ??? ??? ??? ?????.
    org.springframework.data.mongodb: DEBUG # Spring Data MongoDB ?? ??? DEBUG ??? ?????.
